Make unknown and internal command messages customisable
Electroid/SportPaper pull request #44
Opened 2020-12-04 12:04 UTC by VytskaLT

Makes the unknown command and internal error messages customisable in PlayerCommandPreprocessEvent. Useful for multi-language servers.

2020-12-29 21:51 UTC, AustinLMayes requested changes

2020-12-29 21:51 UTC, AustinLMayes commented on patches/api/0101-Make-unknown-and-internal-command-messages-customisa.patch
> ++        this.unknownCommandMessage = unknownCommandMessage;
This needs null and empty validation.

2020-12-29 21:51 UTC, AustinLMayes commented on patches/api/0101-Make-unknown-and-internal-command-messages-customisa.patch
> ++        this.internalErrorMessage = internalErrorMessage;
This needs null and empty validation.

2020-12-29 21:51 UTC, AustinLMayes commented on patches/server/0193-Make-unknown-and-internal-command-messages-customisa.patch
> ++    public boolean dispatchCommand(CommandSender sender, String commandLine) throws CommandException {
Don't need the `throws`

2020-12-29 21:51 UTC, AustinLMayes commented on patches/server/0193-Make-unknown-and-internal-command-messages-customisa.patch
> ++                org.bukkit.ChatColor.RED + "An internal error occurred while attempting to perform this command");
Make this configurable via config as well

2021-02-21 15:13 UTC, VytskaLT commented
Can this be reviewed?

2021-03-19 02:28 UTC, Electroid commented
So this is kinda off-spec with newer Spigot/Paper, but I think its a fine addition. GTM

2021-03-19 02:33 UTC, merged